### ISSUE TITLE
証明書エラーで起動しない事例対応

### ISSUE THREAD

**Issue by Shunshun94** [Shunshun94/discord-bcdicebot#157]
```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Websocket closed before READY packet was received!
        at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
        at java.util.concurrent.CompletableFuture.get(Unknown Source)
        at [http://com.hiyoko.discord.bot](https://t.co/ndDxQVwzeg).BCDice.BCDiceBot.<init>([http://BCDiceBot.java:103](https://t.co/mbD7qsLYnx))
        at [http://com.hiyoko.discord.bot](https://t.co/ndDxQVwzeg).BCDice.BCDiceBot.main(https://t.co/E7i9YuAjqf)
Caused by: java.lang.IllegalStateException: Websocket closed before READY packet was received!
        at org.javacord.core.DiscordApiImpl.lambda$new$6([http://DiscordApiImpl.java:664](https://t.co/WOEJwsXxuz))
        at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.util.concurrent.CompletableFuture.complete(Unknown Source)
        at org.javacord.core.util.gateway.DiscordWebSocketAdapter.onDisconnected([http://DiscordWebSocketAdapter.java:515](https://t.co/mdAiT7DdGM))
        at [http://com.neovisionaries.ws](https://t.co/3p4urgpWnI).client.ListenerManager.callOnDisconnected(https://t.co/FQvyELQ6hZ)
        at [http://com.neovisionaries.ws](https://t.co/3p4urgpWnI).client.WebSocket.finish(https://t.co/yYI662nHLj)
        at [http://com.neovisionaries.ws](https://t.co/3p4urgpWnI).client.WebSocket.onThreadsFinished(https://t.co/LziwLrHZL7)
        at [http://com.neovisionaries.ws](https://t.co/3p4urgpWnI).client.WebSocket.onWritingThreadFinished(https://t.co/r1X6mfATtN)
        at [http://com.neovisionaries.ws](https://t.co/3p4urgpWnI).client.WritingThread.notifyFinished(https://t.co/KwwXCLGOhl)
        at [http://com.neovisionaries.ws](https://t.co/3p4urgpWnI).client.WritingThread.runMain(https://t.co/Q0XSH49oBJ)
        at http://com.neovisionaries.ws.client.WebSocketThread.run(https://t.co/oQi7ctioXX)
```

validate.bat の結果は以下の通りとのことなので証明書の問題だと思うが対処法がわからない。
```
===Ensuring Token is valid / Token の妥当性確認===
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - 失効の関数は証明書の失効を確認 できませんでした。
Invalid Token. / Token の値が間違っています
Press any key to continue . . .
```

**Comment by Shunshun94** [comment]
![image](https://user-images.githubusercontent.com/16047644/196016535-1e5652e7-2eee-4eb3-98f8-f673a843a755.png)
Baltmore CyberTrust Root の証明書を確認できているか確認するのが良いだろうか。

**Comment by danyalutsevich** [comment]
yo are you alive?
check your twitter DM texted you like a year ago
