### ISSUE TITLE
なんかダウンする

### ISSUE THREAD

**Issue by Shunshun94** [Shunshun94/discord-bcdicebot#42]
ずっと動かしている bot が22～24時くらいにダウンし、
5～10分くらいで復旧する現象がある。

ここ最近毎日なのでなんとかしたい。

Bot がログインしていない状態になるので Discord - Bot アプリ間の通信が死んでると思われる。
しかし、プロセスは動いているし数分で回復するのでネットワークの瞬断か何かか？

**Comment by Shunshun94** [comment]
```
2020-05-13 17:42:35.163+0000 WARN org.javacord.core.util.gateway.DiscordWebSocketAdapter Websocket error! {shard=0} 
 com.neovisionaries.ws.client.WebSocketException: An I/O error occurred while a frame was being read from the web socket: Connection timed out (Read failed)
        at com.neovisionaries.ws.client.ReadingThread.readFrame(ReadingThread.java:375)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:99)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
Caused by: javax.net.ssl.SSLException: Connection timed out (Read failed)
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:269)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
        at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1306)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:832)
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
        at com.neovisionaries.ws.client.WebSocketInputStream.readBytes(WebSocketInputStream.java:165)
        at com.neovisionaries.ws.client.WebSocketInputStream.readFrame(WebSocketInputStream.java:46)
        at com.neovisionaries.ws.client.ReadingThread.readFrame(ReadingThread.java:338)
        ... 3 more
        Suppressed: java.net.SocketException: Broken pipe (Write failed)
                at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
                at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
                at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
                at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
                at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:357)
                ... 14 more
Caused by: java.net.SocketException: Connection timed out (Read failed)
        at java.base/java.net.SocketInputStream.socketRead0(Native Method)
        at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
        at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1096)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:816)
        ... 10 more
2020-05-13 17:42:35.166+0000 INFO org.javacord.core.util.gateway.DiscordWebSocketAdapter Websocket closed with reason 'Heartbeat was not answered properly' and code UNKNOWN_ERROR (4000) by client! {shard=0} 
2020-05-13 17:42:35.166+0000 INFO org.javacord.core.util.gateway.DiscordWebSocketAdapter Trying to reconnect/resume in 1 seconds! {shard=0} 
2020-05-13 17:42:36.324+0000 INFO org.javacord.core.util.gateway.DiscordWebSocketAdapter Could not resume session. Reconnecting in 1.8 seconds... {shard=0}
```

**Comment by Shunshun94** [comment]
```
2020-05-07 09:20:39.186+0000 WARN org.javacord.core.util.gateway.DiscordWebSocketAdapter Websocket error! {shard=0}
 
 com.neovisionaries.ws.client.WebSocketException: Flushing frames to the server failed: Connection or outbound has 
closed
        at com.neovisionaries.ws.client.WritingThread.doFlush(WritingThread.java:434)
--
2020-05-07 09:20:39.280+0000 WARN org.javacord.core.util.gateway.DiscordWebSocketAdapter Websocket error! {shard=0}
 
 com.neovisionaries.ws.client.WebSocketException: Flushing frames to the server failed: Connection or outbound has 
closed
        at com.neovisionaries.ws.client.WritingThread.doFlush(WritingThread.java:434)
--
2020-05-07 09:20:59.085+0000 WARN org.javacord.core.util.gateway.DiscordWebSocketAdapter Websocket error! {shard=0}
 
 com.neovisionaries.ws.client.WebSocketException: Flushing frames to the server failed: Connection or outbound has 
closed
        at com.neovisionaries.ws.client.WritingThread.doFlush(WritingThread.java:434)
--
2020-05-07 09:20:59.086+0000 WARN org.javacord.core.util.gateway.DiscordWebSocketAdapter Websocket error! {shard=0}
 
 com.neovisionaries.ws.client.WebSocketException: Flushing frames to the server failed: Connection or outbound has 
closed
        at com.neovisionaries.ws.client.WritingThread.doFlush(WritingThread.java:434)
```

**Comment by Shunshun94** [comment]
久方ぶりに再発

```
14:14:12.048 [Javacord - Central ExecutorService - 614] DEBUG com.hiyoko.discord.bot.BCDice.BCDiceCLI - bot send command to server: 4
14:14:12.751 [Javacord - Central ExecutorService - 614] DEBUG com.hiyoko.discord.bot.BCDice.BCDiceBot - Dice command request for dice server is done
2020-08-25 14:31:48.924+0000 WARN org.javacord.core.util.gateway.DiscordWebSocketAdapter Websocket error! {shard=0} 
 com.neovisionaries.ws.client.WebSocketException: An I/O error occurred while a frame was being read from the web socket: Connection timed out (Read failed)
        at com.neovisionaries.ws.client.ReadingThread.readFrame(ReadingThread.java:375)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:99)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
Caused by: javax.net.ssl.SSLException: Connection timed out (Read failed)
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:269)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
        at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1306)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:832)
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
        at com.neovisionaries.ws.client.WebSocketInputStream.readBytes(WebSocketInputStream.java:165)
        at com.neovisionaries.ws.client.WebSocketInputStream.readFrame(WebSocketInputStream.java:46)
        at com.neovisionaries.ws.client.ReadingThread.readFrame(ReadingThread.java:338)
        ... 3 more
        Suppressed: java.net.SocketException: Broken pipe (Write failed)
                at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
                at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
                at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
                at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
                at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:357)
                ... 14 more
Caused by: java.net.SocketException: Connection timed out (Read failed)
        at java.base/java.net.SocketInputStream.socketRead0(Native Method)
        at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
        at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1096)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:816)
        ... 10 more
2020-08-25 14:31:48.955+0000 INFO org.javacord.core.util.gateway.DiscordWebSocketAdapter Websocket closed with reason 'Heartbeat was not answered properly' and code UNKNOWN_ERROR (4000) by client! {shard=0} 
2020-08-25 14:31:48.979+0000 INFO org.javacord.core.util.gateway.DiscordWebSocketAdapter Trying to reconnect/resume in 1 seconds! {shard=0} 
2020-08-25 14:31:50.341+0000 INFO org.javacord.core.util.gateway.DiscordWebSocketAdapter Could not resume session. Reconnecting in 4.3 seconds... {shard=0} 
14:32:02.651 [Javacord - Central ExecutorService - 614] DEBUG com.hiyoko.discord.bot.BCDice.BCDiceBot - 210264814289682443 posts: https://discordapp.com/channels/463088353794064384/731084522225008640/747825623279337483
14:32:02.651 [Javacord - Central ExecutorService - 614] DEBUG com.hiyoko.discord.bot.BCDice.BCDiceCLI - bot send command to server: 18
14:32:03.534 [Javacord - Central ExecutorService - 614] DEBUG com.hiyoko.discord.bot.BCDice.BCDiceBot - Dice command request for dice server is done
```

**Comment by Shunshun94** [comment]
https://github.com/TakahikoKawasaki/nv-websocket-client/tree/nv-websocket-client-2.10#create-websocket

Javacord がつかっているライブラリはこんな感じでタイムアウト値を差し込んでいるらしいが、
これをどうやって javacord に指示できるかな？

**Comment by Shunshun94** [comment]
悲鳴はここで上がっているっぽい？

https://github.com/Javacord/Javacord/blob/v3.0.6/javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java#L878-L892

**Comment by Shunshun94** [comment]
わからんかつ再発してないので一端閉じ
