### ISSUE TITLE
bcdice help SYSTEM_NAME でクラッシュ

### ISSUE THREAD

**Issue by h-mikisato** [Shunshun94/discord-bcdicebot#79]
`bcdice help SwordWorld2.5` と入力したところ、以下のようなスタックトレースを出力しました。他の存在するシステム名でも同様で、逆に存在しないシステム名を入力した場合は正しく `System 'hoge' is not found` と出力されます。

```
Jan 26 01:00:11 tentacle-palace.com start.sh[444620]: 2021-01-26 01:00:11.655+0900 ERROR org.javacord.core.util.event.EventDispatcherBase Unhandled exception in a listener thread for (Server Name)! {shard=0}
Jan 26 01:00:11 tentacle-palace.com start.sh[444620]:  java.lang.NullPointerException
Jan 26 01:00:11 tentacle-palace.com start.sh[444620]:         at com.hiyoko.discord.bot.BCDice.dto.SystemInfo.<init>(SystemInfo.java:30)
Jan 26 01:00:11 tentacle-palace.com start.sh[444620]:         at com.hiyoko.discord.bot.BCDice.DiceClient.BCDiceV2Client.getSystemInfo(BCDiceV2Client.java:197)
Jan 26 01:00:11 tentacle-palace.com start.sh[444620]:         at com.hiyoko.discord.bot.BCDice.BCDiceCLI.inputs(BCDiceCLI.java:321)
Jan 26 01:00:11 tentacle-palace.com start.sh[444620]:         at com.hiyoko.discord.bot.BCDice.BCDiceBot.lambda$null$3(BCDiceBot.java:79)
Jan 26 01:00:11 tentacle-palace.com start.sh[444620]:         at org.javacord.core.util.event.EventDispatcher.lambda$dispatchMessageCreateEvent$102(EventDispatcher.java:3636)
Jan 26 01:00:11 tentacle-palace.com start.sh[444620]:         at org.javacord.core.util.event.EventDispatcherBase.lambda$dispatchEvent$10(EventDispatcherBase.java:197)
Jan 26 01:00:11 tentacle-palace.com start.sh[444620]:         at org.javacord.core.util.event.EventDispatcherBase.lambda$checkRunningListenersAndStartIfPossible$17(EventDispatcherBase.java:265)
Jan 26 01:00:11 tentacle-palace.com start.sh[444620]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
Jan 26 01:00:11 tentacle-palace.com start.sh[444620]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Jan 26 01:00:11 tentacle-palace.com start.sh[444620]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Jan 26 01:00:11 tentacle-palace.com start.sh[444620]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Jan 26 01:00:11 tentacle-palace.com start.sh[444620]:         at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Shunshun94** [comment]
ありがとうございます！本件について修正し、2.0.2 として公開しました。
