### ISSUE TITLE
サーバーのテキストチャットでダイスが振れない

### ISSUE THREAD

**Issue by C0ela** [Shunshun94/discord-bcdicebot#8]
不具合を見つけましたので報告します。

## 症状
* サーバーのテキストチャットでダイスロールの発言をしてもbotが反応しない
* bot宛のDMでダイスロール発言をすると結果がDMに返る

### 起動時に WARN が出る
`
21:11:04.660 [pool-5-thread-1] WARN  d.b.javacord.utils.PacketHandler - Couldn't handle packet of type GUILD_CREATE. Please contact the developer!  (packet: {"default_message_notifications":1,"unavailable":false,"owner_id": ... ※省略※ ... })
org.json.JSONException: JSONObject["type"] not a string.
	at org.json.JSONObject.getString(JSONObject.java:658) ~[discord-bcdicebot.jar:na]
	at de.btobastian.javacord.entities.impl.ImplServer.<init>(ImplServer.java:111) ~[discord-bcdicebot.jar:na]
	at de.btobastian.javacord.utils.handler.server.GuildCreateHandler.handle(GuildCreateHandler.java:59) ~[discord-bcdicebot.jar:na]
	at de.btobastian.javacord.utils.PacketHandler$1.run(PacketHandler.java:71) ~[discord-bcdicebot.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
`
### テキストチャットでの発言時にWARNが出る
`
21:24:17.892 [pool-4-thread-1] WARN  d.b.j.u.h.m.MessageCreateHandler - Uncaught exception in MessageCreateListener!
java.lang.NullPointerException: null
	at de.btobastian.javacord.entities.message.impl.ImplMessage.reply(ImplMessage.java:366) ~[discord-bcdicebot.jar:na]
	at com.hiyoko.discord.bot.BCDice.BCDiceBot$1$1.onMessageCreate(BCDiceBot.java:46) ~[discord-bcdicebot.jar:na]
	at de.btobastian.javacord.utils.handler.message.MessageCreateHandler$1.run(MessageCreateHandler.java:66) ~[discord-bcdicebot.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
`

9月前半に使ったときは問題なく動いていましたが、ここ1、2週間でこの様な状態になりました。
対処の方法がよく分かりませんでしたのでメッセージの内容を全文貼らせて頂きます。

**Comment by Shunshun94** [comment]
@C0ela さん

ありがとうございます！

手元では同様の問題を再現することができませんでしたが、
同様の問題とその解決事例から推測して一旦の修正を試みたものをアップロードしました。
お手数ですが、ご確認いただければと思います。

https://drive.google.com/file/d/0BwmXeRuZhw9oUzBINlJUdEp2eGM/view?usp=sharing

よろしくお願いいたします。

**Comment by C0ela** [comment]
@Shunshun94 

早速のご対応をありがとうございます！
discord-bcdicebot.jar を修正版に差し替えたら無事にテキストチャットでも動作しました。
今のところ確認できる範囲では上記WARNを始めエラー等発生していません。有難うございます。
